version: '3.7'

services:
#nginx
  www:
    build:
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/conf.d/default.conf/:/etc/nginx/conf.d/default.conf # sync project dir with container web dir
    ports:
      - 80:80
      - 443:443
#php      
  app:
    build:
      dockerfile: ./php/Dockerfile    
#db
  db:
    image: mysql:8.0
    # volumes:
    #   - mysqldata:/var/lib/mysql
    restart: unless-stopped    
    environment:
      MYSQL_ROOT_PASSWORD: korleone9070
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: docker-db


#redis

#variables
# volumes:
#   mysqldata: